# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a93f376b53a483eff9e72930d094b65eb04cd205b6b446d5ccfc59f64b3fb4bef0ae7c9ce63c2678d1c5e325e7055ccda4ad93572aa38e0e226640d914a9b82e

test:
  secret_key_base: 5bc08fba7f667968a273a0e4af9336a959608bb6822452f71407316f0d315acd2159baa1975b1f311ba859357f4a80f11557a18a799b6ac1c2cd66bb16463ef4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
